# Site settings
title: Snarqie
header-img: img/default-bg.jpg
email: snarqie@snarqie.com
description: "Underdog YouTuber"
baseurl:
url: "http://www.snarqie.com"
twitter_username: snarqie
github_username: snarqie
facebook_username: snarqie

# Build settings
markdown: kramdown
highlighter: pygments
permalink: none
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
