# Plugins
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jemoji

# Site settings
title: Snarqie
header-img: "img/default-bg.jpg"
meta-img: "img/default-meta.jpg"
email: snarqie@snarqie.com
description: "Gamer, desenvolvedor web, m√∫sico, youtuber (TGN Army/TGN - BroadbandTV Partner) e blogueiro nas horas vagas"
meta-robots: "noodp, noydir, index, follow"
url: "https://www.snarqie.com"
baseurl: ""
twitch_username: snarqie
twitter_username: snarqie
github_username: snarqie
facebook_username: snarqie

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/
paginate_path: "/pagina-:num"
paginate: 5
timezone: America/Fortaleza
exclude: ["less","node_modules"]

jekyll-mentions: https://twitter.com