# Site settings
title: Snarqie
header-img: img/default-bg.jpg
email: snarqie@snarqie.com
description: "Underdog YouTuber"
url: "http://www.snarqie.com"
twitter_username: snarqie
github_username: snarqie
facebook_username: snarqie

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/
paginate: 5
timezone: America/Fortaleza
exclude: ["less","node_modules","Gruntfile.js","package.json"]

gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jemoji