# Plugins
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-archives
- jekyll-redirect-from
- jemoji

# Site settings
title: Snarqie
header-img: "img/default-bg.jpg"
email: snarqie@snarqie.com
description: "Gamer, desenvolvedor web, m√∫sico, youtuber (TGN Army/TGN - BroadbandTV Partner) e blogueiro nas horas vagas"
url: "//www.snarqie.com"
baseurl: ""
twitch_username: snarqie
twitter_username: snarqie
github_username: snarqie
facebook_username: snarqie

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/
paginate: 5
timezone: America/Fortaleza
exclude: ["less","node_modules","Gruntfile.js","package.json"]

jekyll-mentions: https://twitter.com
jekyll-archives:
  enabled: all
  layouts: 'archive'
  permalinks:
    year: '/arquivo/:year/'
    month: '/arquivo/:year/:month/'
    day: '/arquivo/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/:name/'